const WMI_DB = {
    // 🇯🇵 ياباني
    'JTD': { make: 'تويوتا', icon: '🚙', country: 'اليابان' },
    'JT2': { make: 'تويوتا', icon: '🚙', country: 'اليابان' },
    'JT1': { make: 'تويوتا', icon: '🚙', country: 'اليابان' },
    'JTH': { make: 'لكزس', icon: '🏎️', country: 'اليابان' },
    'JTJ': { make: 'لكزس', icon: '🏎️', country: 'اليابان' },
    'JN1': { make: 'نيسان', icon: '🚗', country: 'اليابان' },
    'JN8': { make: 'نيسان', icon: '🚗', country: 'اليابان' },
    'JNK': { make: 'انفينيتي', icon: '🚗', country: 'اليابان' },
    'JHM': { make: 'هوندا', icon: '🚘', country: 'اليابان' },
    'JH4': { make: 'اكيورا', icon: '🚘', country: 'اليابان' },
    'JM1': { make: 'مازدا', icon: '🚗', country: 'اليابان' },
    'JM3': { make: 'مازدا', icon: '🚗', country: 'اليابان' },
    'JA3': { make: 'ميتسوبيشي', icon: '🚙', country: 'اليابان' },
    'JA4': { make: 'ميتسوبيشي', icon: '🚙', country: 'اليابان' },
    'JSA': { make: 'سوزوكي', icon: '🚗', country: 'اليابان' },
    'JS1': { make: 'سوزوكي', icon: '🚗', country: 'اليابان' },
    'JF1': { make: 'سوبارو', icon: '🚗', country: 'اليابان' },
    'JF2': { make: 'سوبارو', icon: '🚗', country: 'اليابان' },
    'JAA': { make: 'ايسوزو', icon: '🚛', country: 'اليابان' },
    'JAB': { make: 'ايسوزو', icon: '🚛', country: 'اليابان' },
    'JDA': { make: 'دايهاتسو', icon: '🚗', country: 'اليابان' },

    // 🇰🇷 كوري
    'KMH': { make: 'هيونداي', icon: '🚘', country: 'كوريا' },
    'KNA': { make: 'كيا', icon: '🚘', country: 'كوريا' },
    'KND': { make: 'كيا', icon: '🚘', country: 'كوريا' },
    'KMT': { make: 'جينيسيس', icon: '🚙', country: 'كوريا' },
    'KNJ': { make: 'كيا', icon: '🚘', country: 'كوريا' },

    // 🇺🇸 أمريكي
    '1FA': { make: 'فورد', icon: '🚘', country: 'أمريكا' },
    '1FT': { make: 'فورد', icon: '🚛', country: 'أمريكا' },
    '1FM': { make: 'فورد', icon: '🚘', country: 'أمريكا' },
    '1G1': { make: 'شيفروليه', icon: '🚙', country: 'أمريكا' },
    '1GC': { make: 'شيفروليه', icon: '🚛', country: 'أمريكا' },
    '1GT': { make: 'GMC', icon: '🚙', country: 'أمريكا' },
    '1GD': { make: 'GMC', icon: '🚛', country: 'أمريكا' },
    '1G6': { make: 'كاديلاك', icon: '🚙', country: 'أمريكا' },
    '1C3': { make: 'كرايسلر', icon: '🚗', country: 'أمريكا' },
    '1C4': { make: 'دودج', icon: '🚗', country: 'أمريكا' },
    '1C6': { make: 'رام', icon: '🚛', country: 'أمريكا' },
    '1J4': { make: 'جيب', icon: '🚙', country: 'أمريكا' },
    '5YJ': { make: 'تسلا', icon: '🚗', country: 'أمريكا' },
    '1LN': { make: 'لينكولن', icon: '🚙', country: 'أمريكا' },
    '2C3': { make: 'كرايسلر', icon: '🚗', country: 'أمريكا' },
    '2C4': { make: 'دودج', icon: '🚗', country: 'أمريكا' },

    // 🇩🇪 ألماني
    'WDD': { make: 'مرسيدس-بنز', icon: '🚙', country: 'ألمانيا' },
    'WDB': { make: 'مرسيدس-بنز', icon: '🚙', country: 'ألمانيا' },
    'WBA': { make: 'BMW', icon: '🚙', country: 'ألمانيا' },
    'WBS': { make: 'BMW M', icon: '🚙', country: 'ألمانيا' },
    'WAU': { make: 'أودي', icon: '🚙', country: 'ألمانيا' },
    'WVW': { make: 'فولكس واجن', icon: '🚗', country: 'ألمانيا' },
    'WVG': { make: 'فولكس واجن', icon: '🚙', country: 'ألمانيا' },
    'WP0': { make: 'بورش', icon: '🏎️', country: 'ألمانيا' },
    'WUA': { make: 'أودي سبورت', icon: '🚙', country: 'ألمانيا' },
    'WBY': { make: 'BMW i', icon: '🚙', country: 'ألمانيا' },

    // 🇬🇧 بريطاني
    'SAL': { make: 'لاند روفر', icon: '🚙', country: 'بريطانيا' },
    'SAJ': { make: 'جاكوار', icon: '🚙', country: 'بريطانيا' },
    'SCB': { make: 'بنتلي', icon: '🚙', country: 'بريطانيا' },
    'SCA': { make: 'رولز رويس', icon: '🚙', country: 'بريطانيا' },
    'SFD': { make: 'أستون مارتن', icon: '🏎️', country: 'بريطانيا' },
    'SBM': { make: 'ماكلارين', icon: '🏎️', country: 'بريطانيا' },
    'SAR': { make: 'رينج روفر', icon: '🚙', country: 'بريطانيا' },

    // 🇸🇪 سويدي
    'YV1': { make: 'فولفو', icon: '🚗', country: 'السويد' },
    'YS3': { make: 'ساب', icon: '🚗', country: 'السويد' },
    'YSM': { make: 'بولستار', icon: '🚗', country: 'السويد' },

    // 🇮🇹 إيطالي
    'ZFF': { make: 'فيراري', icon: '🏎️', country: 'إيطاليا' },
    'ZAM': { make: 'مازيراتي', icon: '🚙', country: 'إيطاليا' },
    'ZAR': { make: 'ألفا روميو', icon: '🚗', country: 'إيطاليا' },
    'ZFA': { make: 'فيات', icon: '🚗', country: 'إيطاليا' },
    'ZHW': { make: 'لامبورغيني', icon: '🏎️', country: 'إيطاليا' },

    // 🇫🇷 فرنسي
    'VF1': { make: 'رينو', icon: '🚗', country: 'فرنسا' },
    'VF3': { make: 'بيجو', icon: '🚗', country: 'فرنسا' },
    'VF7': { make: 'سيتروين', icon: '🚗', country: 'فرنسا' },
    'VR3': { make: 'DS', icon: '🚗', country: 'فرنسا' },

    // 🇨🇳 صيني
    'LSC': { make: 'شانجان', icon: '🚗', country: 'الصين' },
    'L6T': { make: 'جيلي', icon: '🚗', country: 'الصين' },
    'LSJ': { make: 'جيلي', icon: '🚗', country: 'الصين' },
    'LVV': { make: 'شيري', icon: '🚗', country: 'الصين' },
    'LGW': { make: 'جريت وول', icon: '🚗', country: 'الصين' },
    'LMG': { make: 'MG', icon: '🚗', country: 'الصين' },
    'LRW': { make: 'تسلا الصين', icon: '🚗', country: 'الصين' },
    'LSG': { make: 'شيفروليه صيني', icon: '🚗', country: 'الصين' },
    'LSV': { make: 'فولكس واجن صيني', icon: '🚗', country: 'الصين' },
    'LJD': { make: 'BYD', icon: '🚗', country: 'الصين' },
    'LNB': { make: 'BAIC', icon: '🚗', country: 'الصين' },
    'LJ8': { make: 'GAC', icon: '🚗', country: 'الصين' },
    'LZE': { make: 'JAC', icon: '🚗', country: 'الصين' },
    'LBV': { make: 'BMW صيني', icon: '🚙', country: 'الصين' },
    'LE4': { make: 'مرسيدس صيني', icon: '🚙', country: 'الصين' },
    'LKG': { make: 'هافال', icon: '🚗', country: 'الصين' },
    'LNB': { make: 'BAIC', icon: '🚗', country: 'الصين' },
    'LZW': { make: 'شيري تيجو', icon: '🚗', country: 'الصين' },
    'LDC': { make: 'دونغ فينغ', icon: '🚗', country: 'الصين' },
};
